name: Deploy Pipeline to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy via AWS SSM
        run: |
          cat > params.json << 'EOF'
          {
            "commands": [
              "which git || (apt-get update -y && apt-get install -y git)",
              "if [ -d /home/ubuntu/cloud-event-pipeline ]; then cd /home/ubuntu/cloud-event-pipeline && git pull; else git clone https://github.com/Naved124/cloud-event-pipeline.git /home/ubuntu/cloud-event-pipeline; fi",
              "echo DB_USER=${{ secrets.DB_USER }} > /home/ubuntu/cloud-event-pipeline/.env",
              "echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> /home/ubuntu/cloud-event-pipeline/.env",
              "echo DB_NAME=${{ secrets.DB_NAME }} >> /home/ubuntu/cloud-event-pipeline/.env",
              "docker compose -f /home/ubuntu/cloud-event-pipeline/docker-compose.yml down",
              "docker compose -f /home/ubuntu/cloud-event-pipeline/docker-compose.yml up -d --build"
            ]
          }
          EOF
          
          COMMAND_ID=$(aws ssm send-command \
            --targets "Key=tag:Name,Values=CloudEventPipelineServer" \
            --document-name "AWS-RunShellScript" \
            --parameters file://params.json \
            --query "Command.CommandId" \
            --output text)
            
          echo "Command queued with ID: $COMMAND_ID"
          
          # Wait 5 seconds to ensure AWS registers the instance state
          sleep 5 
          
          INSTANCE_ID=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=CloudEventPipelineServer" "Name=instance-state-name,Values=running" \
            --query "Reservations[0].Instances[0].InstanceId" \
            --output text)
            
          # Safety check to prevent the 'None' regex crash
          if [ "$INSTANCE_ID" == "None" ] || [ -z "$INSTANCE_ID" ]; then
            echo "Error: No running instance found with tag Name=CloudEventPipelineServer."
            echo "Did you run 'terraform apply'?"
            exit 1
          fi
            
          echo "Waiting for execution on instance: $INSTANCE_ID..."
          
          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id "$INSTANCE_ID"