name: Deploy Pipeline to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy via AWS SSM
        run: |
          cat > params.json << 'EOF'
          {
            "commands": [
              "which git || (apt-get update -y && apt-get install -y git)",
              "if [ -d /home/ubuntu/cloud-event-pipeline ]; then cd /home/ubuntu/cloud-event-pipeline && git pull; else git clone https://github.com/Naved124/cloud-event-pipeline.git /home/ubuntu/cloud-event-pipeline; fi",
              "echo DB_USER=${{ secrets.DB_USER }} > /home/ubuntu/cloud-event-pipeline/.env",
              "echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> /home/ubuntu/cloud-event-pipeline/.env",
              "echo DB_NAME=${{ secrets.DB_NAME }} >> /home/ubuntu/cloud-event-pipeline/.env",
              "docker compose -f /home/ubuntu/cloud-event-pipeline/docker-compose.yml down",
              "docker compose -f /home/ubuntu/cloud-event-pipeline/docker-compose.yml up -d --build"
            ]
          }
          EOF
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --parameters file://params.json \
            --output text
            # Capture the resulting CommandId
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --parameters file://params.json \
            --query "Command.CommandId" \
            --output text)
            
          echo "Waiting for command $COMMAND_ID to finish execution on the server..."
          
          # Block the pipeline until the server reports Success or Failed
          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id "${{ secrets.EC2_INSTANCE_ID }}"